name: field_asistence
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.2
  path_provider: ^2.1.3
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  get: 4.6.5
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.2
  carousel_slider: ^4.2.1
  animations: ^2.0.11
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  file_picker: ^8.0.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  firebase_messaging: ^15.0.2
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^5.0.0
  otp_autofill: ^3.0.2
  sms_autofill: ^2.4.0
  dio: ^5.5.0+1
  babstrap_settings_screen: ^0.1.6
  month_picker_dialog: ^4.0.1
  syncfusion_flutter_charts: ^25.1.41+1
  infinite_scroll_pagination: ^4.0.0
  sembast: ^3.7.1
  dropdown_search: ^5.0.6
  flutter_swipe_button: ^2.1.1+1
  package_info_plus: ^6.0.0
  fl_chart: ^0.68.0
  animate_do: ^3.3.4
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  generate: true
  


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/annimations/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

  