name: field_asistence
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  flutter_local_notifications: ^18.0.1
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.1.0
  intl: ^0.20.2
  provider: ^6.1.2
  path_provider: ^2.1.3
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  get_it: ^8.0.3
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.2
  carousel_slider: ^5.0.0
  animations: ^2.0.11
  device_info_plus: ^11.3.0
  connectivity_plus: ^6.0.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  file_picker: ^8.0.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.0
  flutter_map_marker_cluster: ^1.3.6
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  location: ^8.0.0
  firebase_messaging: ^15.0.2
  flutter_staggered_grid_view: ^0.7.0
  pinput: ^5.0.0
  otp_autofill: ^4.1.0
  sms_autofill: ^2.4.0
  dio: ^5.5.0+1
  month_picker_dialog: ^6.0.2
  syncfusion_flutter_charts: ^28.2.5+1
  infinite_scroll_pagination: ^4.0.0
  sembast: ^3.7.1
  dropdown_search: ^6.0.2
  flutter_swipe_button: ^2.1.2
  package_info_plus: ^8.2.1
  fl_chart: ^0.70.2
  animate_do: ^4.0.1
  visibility_detector: ^0.4.0+2
  scrollable_positioned_list: ^0.3.8
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^4.0.0
  flutter_background: ^1.3.0
  latlong2: ^0.9.1
  flutter_image_compress: ^2.3.0
  speech_to_text: ^7.0.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  generate: true
  


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/annimations/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

  